FeatureSettings:
  description: Base feature settings. Only the feature settings corresponding to the feature specified in the featureType field is or should be present.
  discriminator: featureType
  required:
    - featureType
  properties:
    featureType:
      description: Feature type code
      type: string
    originatorFeatureSetIndex:
      description: Optional for reverse API. This is the feature set index from where the message comes from.
      type: integer
    originatorFeatureIndex:
      description: Optional for reverse API. This is the feature index from where the message comes from.
      type: integer
    AFCSettings:
      $ref: "/doc/swagger/include/AFC.yaml#/AFCSettings"
    GS232ControllerSettings:
      $ref: "/doc/swagger/include/GS232Controller.yaml#/GS232ControllerSettings"
    SimplePTTSettings:
      $ref: "/doc/swagger/include/SimplePTT.yaml#/SimplePTTSettings"
    RigCtlServerSettings:
      $ref: "/doc/swagger/include/RigCtlServer.yaml#/RigCtlServerSettings"
